apiVersion: v1
kind: PersistentVolume
metadata:
  name: ensimmaeinen-mongodb-volume-production
  labels:
    type: local
    app.kubernetes.io/instance: mongodb-user-service
    environment: production
spec:
  storageClassName: ""
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/production/mongodb/yksi"
